const MODULE_PREFIX = 'ORGANIZATION/API_KEYS';

export const SET_LOADING = `${MODULE_PREFIX}/SET_LOADING`;
export const SET_API_KEYS = `${MODULE_PREFIX}/SET_API_KEYS`;
export const SET_API_KEY_FORM = `${MODULE_PREFIX}/SET_API_KEY_FORM`;
export const RESET_API_KEY_FORM = `${MODULE_PREFIX}/RESET_API_KEY_FORM`;
export const SET_API_KEY_FORM_OPEN = `${MODULE_PREFIX}/SET_API_KEY_FORM_OPEN`;
