export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export const LOGOUT = 'LOGOUT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const SET_GET_USER_DETAILS_LOADING = 'SET_GET_USER_DETAILS_LOADING';
export const SET_USER = 'SET_USER';
export const SET_SIGNUP_LOADING = 'SET_SIGNUP_LOADING';

export const SET_PASSWORD_RESET_LOADING = 'SET_PASSWORD_RESET_LOADING';
export const SET_SUBSCRIBE_TO_API_DOCS_LOADING = 'SET_SUBSCRIBE_TO_API_DOCS_LOADING';
export const SET_USER_API_KEY = 'SET_USER_API_KEY';
