# This file is a template, and might need editing before it works on your project.
before_script:
  - echo "Starting..."
stages:
  - build
  - deploy

# build-master:
#   image: node:10.15.0-jessie
#   stage: build
#   script:
#     - source scripts/build.sh 
#   only:
#     - master

deploy-production:
  image: node:10.15.0-jessie
  stage: deploy
  # dependencies:
  #   - build-master
  script:
    - source scripts/deploy.sh videowiki-staging.org
  when: manual
  only:
    - master

