FROM node:10.21.0-alpine3.11
WORKDIR /client

COPY . .
RUN npm install


# INSTALL NGINX
#RUN apt-get update
#RUN apt-get install -y NGINX
#RUN service nginx start
#RUN systemctl enable nginx
#RUN cp videowiki_nginx.conf /etc/nginx/conf.d

#RUN apt-get upgrade libstdc++6

EXPOSE 3000

CMD ["npm", "run", "dev"]
HEALTHCHECK --start-period=30s --interval=2m CMD wget --quiet --tries=1 localhost:3000  -O /dev/null || exit 1