const MODULE_PREFIX = `NOTIFICATION`

export const SET_UNREAD_COUNT = `${MODULE_PREFIX}/SET_UNREAD_COUNT`;
export const SET_NOTIFICATIONS = `${MODULE_PREFIX}/SET_NOTIFICATIONS`;

export const SET_LOADING = `${MODULE_PREFIX}/SET_LOADING`;

export const SET_CURRENT_PAGE = `${MODULE_PREFIX}/SET_CURRENT_PAGE`;
export const SET_TOTAL_PAGES_COUNT = `${MODULE_PREFIX}/SET_TOTAL_PAGES_COUNT`;