const MODULE_PREFIX = `IMAGE`;

export const SET_UPLOAD_IMAGE_FORM = `${MODULE_PREFIX}/SET_UPLOAD_IMAGE_FORM`;
export const SET_UPLOAD_ACTIVE_TAB_INDEX = `${MODULE_PREFIX}/SET_UPLOAD_ACTIVE_TAB_INDEX`;
export const RESET_UPLOAD_IMAGE_FORM = `${MODULE_PREFIX}/RESET_UPLOAD_IMAGE_FORM`;
export const SET_IMAGES = `${MODULE_PREFIX}/SET_IMAGES`;
export const SET_TOTAL_PAGES_COUNT = `${MODULE_PREFIX}/SET_TOTAL_PAGES_COUNT`;
export const SET_CURRENT_PAGE_NUMBER = `${MODULE_PREFIX}/SET_CURRENT_PAGE_NUMBER`;
export const SET_IMAGES_LOADING = `${MODULE_PREFIX}/SET_IMAGES_LOADING`;
export const SET_SEARCH_FILTER = `${MODULE_PREFIX}/SET_SEARCH_FILTER`;

export const SET_IMAGE = `${MODULE_PREFIX}/SET_IMAGE`;
export const SET_STATUS = `${MODULE_PREFIX}/SET_STATUS`;

export const SET_TRANSLATION_ACTIVE_TAB_INDEX = `${MODULE_PREFIX}/SET_TRANSLATION_ACTIVE_TAB_INDEX`;
export const SET_IMAGE_TRANSLATION_EXPORTS = `${MODULE_PREFIX}/SET_IMAGE_TRANSLATION_EXPORTS`;
export const SET_TRANSLATION_EXPORTS_CURRENT_PAGE = `${MODULE_PREFIX}/SET_TRANSLATION_EXPORTS_CURRENT_PAGE`;
export const SET_TRANSLATION_EXPORTS_TOTAL_PAGES = `${MODULE_PREFIX}/SET_TRANSLATION_EXPORTS_TOTAL_PAGES`;
