const MODULE_PREFIX = 'ORGANIZATION/TASKS';

export const SET_LOADING = `${MODULE_PREFIX}/SET_LOADING`;

export const SET_CURRENT_PAGE_NUMBER = `${MODULE_PREFIX}/SET_CURRENT_PAGE_NUMBER`;
export const SET_TOTAL_PAGES_COUNT = `${MODULE_PREFIX}/SET_TOTAL_PAGES_COUNT`;

export const SET_ARTICLES = `${MODULE_PREFIX}/SET_ARTICLES`

export const SET_SEARCH_FILTER = `${MODULE_PREFIX}/SET_SEARCH_FILTER`;
export const SET_VIDEOS = `${MODULE_PREFIX}/SET_VIDEOS`;
export const SET_VIDEO_STATUS_FILTER = `${MODULE_PREFIX}/SET_VIDEO_STATUS_FILTER`;
export const SET_FETCH_FROM_ALL_ORGANIZATIONS = `${MODULE_PREFIX}/SET_FETCH_FROM_ALL_ORGANIZATIONS`;
