const MODULE_PREFIX = 'ARTICLE'

export const FETCH_ARTICLE_LOADING = `${MODULE_PREFIX}/FETCH_ARTICLE_LOADING`;
export const FETCH_ARTICLE_FAILED = `${MODULE_PREFIX}/FETCH_ARTICLE_FAILED`;
export const FETCH_ARTICLE_SUCCESS = `${MODULE_PREFIX}/FETCH_ARTICLE_SUCCESS`;

export const UPDATE_SUBSLIDE_LOADING = `${MODULE_PREFIX}/UPDATE_SUBSLIDE_LOADING`;
export const UPDATE_SUBSLIDE_FAILED = `${MODULE_PREFIX}/UPDATE_SUBSLIDE_FAILED`;
export const UPDATE_SUBSLIDE_SUCCESS = `${MODULE_PREFIX}/UPDATE_SUBSLIDE_SUCCESS`;

export const SET_SUBTITLES = `${MODULE_PREFIX}/SET_SUBTITLES`;
export const SET_ARTICLE = `${MODULE_PREFIX}/SET_ARTCILE`;
export const SET_SELECTED_SUBTITLE = `${MODULE_PREFIX}/SET_SELECTED_SUBTITLE`;

export const SET_TO_ENGLISH = `${MODULE_PREFIX}/SET_TO_ENGLISH`;
export const SET_NAME_SLIDES = `${MODULE_PREFIX}/SET_NAME_SLIDES`;
export const RESET = `${MODULE_PREFIX}/RESET`;

